### ISSUE TITLE
Build failing for both projects on fresh clone

### ISSUE THREAD

**Issue by brentschooley** [TwilioDevEd/conference-broadcast-csharp#1]
Following the README.md (making one change as Local.config should not have `file` attribute) I cloned the repo and updated config. Upon trying to build, I get a failed build for both projects:

![failed](https://cloud.githubusercontent.com/assets/2213356/10890233/af4a2f6e-814b-11e5-9f57-12ec2f1cde8a.png)

No errors show up in the Errors pane.

**Comment by acamino** [comment]
@brentschooley thanks for pointing out the README is not correct, you're right, I've just opened a PR to fix the misleading step.

I tried to reproduce the error, but on my end it works as expected. Would you mind letting me know which Windows do you have installed. Which version of VS are you using?

Again, thanks for reporting this issue.
